import { Header } from '@/components/layouts/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="fixed z-50 h-[80px] w-full">
          <Header />
        </header>
        <div className="h-[80px] w-full" />
        <main>{children}</main>
      </body>
    </html>
  )
}
